
  package org.example;

    
    
/**
* A real value with a unit.
*
* dataType:  RealQuantity
*
* @author generated by https://github.com/ivoa/vo-dml tools
*/
      @jakarta.persistence.Embeddable



      public  class RealQuantity extends Quantity
      {
      


    /**
    * The real value of this quantity. : Attribute value type ivoa:real : multiplicity 1
    *
    */
    
        @jakarta.persistence.Basic( optional = true )
        @jakarta.persistence.Column( name = "v", nullable = true)
    protected Double v;

      /**
       * Creates a new RealQuantity
       */
      public RealQuantity() {
        super();
      }
      
        /**
        * full parameter constructor.
            
        *   @param value The real value of this quantity.
        *   @param unit The unit of this  quantity.
        */
        public  RealQuantity (
          final Double value, final Unit unit
        )
        {
            super(unit);
           
                       this.v = value;
                   
          }
        

        /**
        * Returns value Attribute.
        * @return value Attribute
        */
        
        public Double getV() {
        
        return (Double)this.v;
            

        }
        
        
        /**
        * Set value Attribute.
        * @param pValue value to set
        */
        public void setV(final Double pValue) {
        
        this.v = pValue;
                

        }





}
  