
package org.example;
        


      /**
      *  Must conform to definition of unit in VOUnit spec.
      *  PrimitiveType Unit :
      *
      *  @author generated by https://github.com/ivoa/vo-dml tools
      */
      
    @jakarta.persistence.Embeddable

      public class  Unit {

      /**
      * no arg constructor.
      */
      protected Unit() {}

      
      /**
      * copy constructor.
      * @param c the object to be copied.
      */
      public Unit(Unit c)
      {
         this(c.u);
      }

      /**  representation */
      private String u;

      /**
      * Creates a new Unit Primitive Type instance, using the base type.
      *
      * @param v the base type.
      */
      public Unit(final String v) {
      this.u = v;
      }
      /**
         * Return the representation of this primitive (value)
         * @return string representation of this primitive( value)
         */
        public final String value() {
            return this.u;
        }

        /**
         * Return the string representation of this primitive value
         * @see #value()
         * @return string representation of this primitive
         */
        @Override
        public final String toString() {
            return value();
        }
      

      }
  